---
galaxy_info:
  role_name: common
  author: Bauer Group
  description: Common base configuration for all managed hosts
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [focal, jammy, noble]
    - name: Debian
      versions: [bullseye, bookworm]
    - name: EL
      versions: [8, 9]

dependencies: []
