---
# Common role defaults
common_packages_install: true
common_timezone_configure: true
common_ntp_configure: true
common_motd_configure: true
common_logdir_configure: true

# SSH hardening (disabled by default - enable per host only!)
# Will REFUSE to harden if no authorized_keys are found for the target user.
common_ssh_hardening: false
common_ssh_permit_root_login: "prohibit-password"
common_ssh_password_authentication: "no"
common_ssh_authorized_keys_user: "root"
