---
# =============================================================================
# Staging Global Variables
# =============================================================================

iac_repo_url: "https://github.com/bauer-group/IAC-Ansible.git"
iac_repo_branch: "staging"

ansible_pull_schedule: "*-*-* 02:00:00"
ansible_pull_playbook: "playbooks/site.yml"

system_timezone: "Etc/UTC"
motd_enabled: true
motd_organization: "BAUER GROUP (STAGING)"
