---
galaxy_info:
  role_name: auto_update
  author: BAUER GROUP
  description: Automatic system updates with controlled reboot scheduling
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
    - name: Debian
      versions: [bookworm, trixie]
    - name: EL
      versions: ["8", "9", "10"]

dependencies:
  - role: common
