---
galaxy_info:
  role_name: auto_update
  author: Bauer Group
  description: Automatic system updates with controlled reboot scheduling
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
    - name: Debian
      versions: [bookworm, trixie]
    - name: EL
      versions: ["8", "9", "10"]

dependencies:
  - role: common
