---
- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart cron
  ansible.builtin.systemd:
    name: "{{ 'cron' if ansible_os_family == 'Debian' else 'crond' }}"
    state: restarted
