---
# =============================================================================
# Ansible-Pull - RedHat/CentOS: Install Ansible
# =============================================================================

- name: "[RedHat] Install EPEL repository"
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: "[RedHat] Install Ansible"
  ansible.builtin.dnf:
    name:
      - ansible
      - git
    state: present
